fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    b2drop: "#{source_dir}"
