sudo: false

language: ruby
rvm:
  - 2.0.0
  - 2.2.0

script: bundle exec rake test

env:
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
