language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false

rvm:
  - 2.0.0
  - 2.2

script: bundle exec rake test

env:
  - PUPPET_GEM_VERSION="~> 4.0.0"
  - PUPPET_GEM_VERSION="~> 4.6.0"
  - PUPPET_GEM_VERSION="~> 4.8.0"

matrix:
  fast_finish: true
